### ISSUE TITLE
bug for _size in CemiLData.cs

### ISSUE THREAD

**Issue by varna2** [toolsfactory/Tiveria.Home.Knx#1]
Hello,

I believe there is a bug in CemiLData.cs: CemiLData(IndividualEndianessBinaryReader br) : base(br) constructor - _size remains undefined.
I think the following line should become part of the constructor:

_size = MESSAGEMINLENGTH + _payload.Length;

Thank you

**Comment by toolsfactory** [comment]
Fixed in the newer releases.
