### ISSUE TITLE
Info on additional testing

### ISSUE THREAD

**Issue by varna2** [toolsfactory/Tiveria.Home.Knx#2]
Hello,

not an issue, just an information from testing - I confirm these APCI types are working (from v1 codebase):

Apci.cs: private static readonly List<APCIEntry> RelevantAPCIEntry = new List<Cemi.APCIEntry>()
...
            new Cemi.APCIEntry(0b1101, 0b000000, 10, APCIType.DeviceDescriptor_Response),
            new Cemi.APCIEntry(0b1111, 0b010110, 10, APCIType.PropertyValue_Response),
...

In current codebase I believe it is this file: src/Tiveria.Home.Knx/Cemi/ApciTypes.cs.

Thank you

**Comment by toolsfactory** [comment]
Thanks. Any feedback always welcome
